### ISSUE TITLE
track_status.py 

### ISSUE THREAD

**Issue by maximuml** [egor-tensin/vk-scripts#1]
urlopen error [Errno 104] Connection reset by peer

**Comment by maximuml** [comment]
[2016-06-07 22:27:40] <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 748, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 984, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 629, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/000bits/online/track_status.py", line 102, in <module>
    loop_update_status(api, args.user_ids, timeout=args.timeout)
  File "/home/000bits/online/track_status.py", line 74, in loop_update_status
    updated_users = list(api.users_get(user_ids, fields))
  File "/home/000bits/online/api.py", line 115, in users_get
    fields=self._format_param_values(fields)))
  File "/home/000bits/online/api.py", line 98, in _call_method
    response = json.loads(urllib.request.urlopen(url).read().decode())
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1286, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1245, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by egor-tensin** [comment]
Yeah, I've bumped into this also, but frankly, thought that nobody would care. I'll fix this later today or tomorrow. Thank you very much for participating.

**Comment by egor-tensin** [comment]
I'm not sure how to reproduce this properly, but I think my ad-hoc fix might be sufficient.

**Comment by maximuml** [comment]
No,  error again 
[2016-06-10 04:21:56] type object 'API' has no attribute 'ConnectionError'
Traceback (most recent call last):
  File "/home/lpbits/online/track_status.py", line 69, in loop_update_status
    updated_users = update_status(api, uids)
  File "/home/lpbits/online/track_status.py", line 58, in update_status
    return {user.get_uid(): user for user in api.users_get(uids, USER_FIELDS)}
  File "/home/lpbits/online/api.py", line 115, in users_get
    fields=self._format_param_values(fields)))
  File "/home/lpbits/online/api.py", line 98, in _call_method
    response = json.loads(urllib.request.urlopen(url).read().decode())
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1286, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1246, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse

**Comment by egor-tensin** [comment]
Yep! Hope I finally got it now, would you mind checking that?

**Comment by maximuml** [comment]
Still error

[2016-06-11 20:31:36] type object 'API' has no attribute 'ConnectionError'
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 748, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 984, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 629, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpbits/online/track_status.py", line 69, in loop_update_status
    updated_users = update_status(api, uids)
  File "/home/lpbits/online/track_status.py", line 58, in update_status
    return {user.get_uid(): user for user in api.users_get(uids, USER_FIELDS)}
  File "/home/lpbits/online/api.py", line 115, in users_get
    if 'response' not in response:
  File "/home/lpbits/online/api.py", line 98, in _call_method
    def _format_method_params(self, *_kwargs):
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 1286, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1245, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpbits/online/track_status.py", line 107, in <module>
    loop_update_status(api, args.uids, timeout=args.timeout)
  File "/home/lpbits/online/track_status.py", line 70, in loop_update_status
    except APIConnectionError:
AttributeError: type object 'API' has no attribute 'ConnectionError'

**Comment by egor-tensin** [comment]
Really don't know what's going on. Do you have the latest versions of all the files, including commit 93eb74a0b77a7761cef795de115cd2b02e67f97d? If you do, try stopping the script and deleting the "__pycache__" directory in the repository's root.

**Comment by maximuml** [comment]
Testing right now. Do you speak russian?

**Comment by egor-tensin** [comment]
Да, конечно.

**Comment by maximuml** [comment]
Ещё раз перекачал скрипт, удалил **pycache**, пока полёт нормальный.

**Comment by egor-tensin** [comment]
Как думаешь, можно закрывать баг?

**Comment by maximuml** [comment]
Думаю да,  второй день нет ошибок. Не знаю к тебе или нет обратится с этим вопросом, но может быть ты знаешь как сделать график статистики на основе данных твоего скрипта? Общее время проведённое в контакте,  разделение по дням, наиболее частое время дня посещение контакта и т.д.

**Comment by egor-tensin** [comment]
Может ты просто скажешь, что тебе хочется видеть, а я сам накидаю скрипты, делающие красивые графики? То, что ты уже перечислил, делается несложно вроде бы, до завтрашнего вечера уже готово будет, заодним попрактикуюсь в Python/matplotlib.

В целом нужно просто поменять скрипт, чтобы он не только писал сообщения в консоль, но и записывал данные о событиях (а-ля "пользователь в сети") с временными пометками куда-нибудь еще; например, в CSV-файл. После этого уже будет просто набросать скрипты, строящие нужные графики с помощью matplotlib. Хотя это даже будет чересчур, наверное; полагаю, что Excel сможет обработать нужным образом, например, CSV-файлы, но не уверен.

В общем, просто скажи, что нужно добавить, мне это в удовольствие.

**Comment by maximuml** [comment]
Как я себе это представляю это график на каждый день недели. Суть графика состоит в том, что бы показать разницу использования контакта в выходные дни и в  будничные,  днём и вечером.

**Comment by maximuml** [comment]
И если пошёл разговор о слежке, есть способ найти лайки пользователя, посты и фотографии?

**Comment by egor-tensin** [comment]
Нет, точно нет; лучший вариант: перебор всего, на что пользователь подписан и перебор всех постов на стене, всех фотографий и т.д. Но и так пропустим все, на что пользователь не подписан.

Между делом, я задержался, но думаю, что сегодня закончу.

**Comment by maximuml** [comment]
Нашёл такой скрипт, но не могу его запустить https://github.com/codeguida/vkutils/tree/master/VKSpySystem

**Comment by egor-tensin** [comment]
Добавил скрипт "online_duration.py". Вроде бы делает то, что тебе нужно (конечно, если я правильно понял). См. README.md для примеров запуска. Поведение "track_status.py" тоже изменилось.

**Comment by egor-tensin** [comment]
С чужими скриптами помочь не могу, извини.

**Comment by maximuml** [comment]
Спасибо, обновил, перезапустил крипт. Отпишусь через день

**Comment by maximuml** [comment]
А есть возможность сделать график на основе информации за сутки? Что-то вроди этого http://www.imagebam.com/gallery/9z0y9s6qcyry24gcst57b562mrxr8aph

**Comment by egor-tensin** [comment]
Добавил, см. README.md. Теперь можно также ограничивать обрабатываемые события из базы по времени.

**Comment by maximuml** [comment]
Спасибо

**Comment by maximuml** [comment]
Последняя ревизия

Traceback (most recent call last):
  File "bin/track_status.py", line 5, in <module>
    from vk.api import API, Language
ImportError: cannot import name 'Language'

**Comment by egor-tensin** [comment]
Теперь запускать нужно с помощью `python -m bin.track_status`. См. README.md и "docs/track_status.md".
